### ISSUE TITLE
'Convert Materials for Cycles' operator randomly crash Blender

### ISSUE THREAD

**Issue by consilium538** [powroupi/blender_mmd_tools#56]
I'm using Blender 2.78a, recent updated version of blender_mmd_tool ( b10cb8c1f2ce0c681d246a7bce9ae7491e925040 ). When I import a model and hit Convert Materials for Cycles button, Blender randomly crash with no notification or alert. In terminal, I can see only EXCEPTION_ACCESS_VIOLATION error. How could I evade this issue?

**Comment by powroupi** [comment]
Thank you for reporting this issue, I will check it. :smile: 

And just some questions:
 - Does it occur in particular model or many models?
 - Will it crash Blender when you hit 'GLSL' button or 'Shadeless' button of 'MMD Shading' panel?
 - (EDIT) Does it still happen when using [sugiany's master version](https://github.com/sugiany/blender_mmd_tools/tree/master)?

**Comment by consilium538** [comment]
Thank's for quick reply. 
Answer for questions
- Q : Does it occur in particular model or many models?
  A : Yes. I've try with Tda type Miku( https://bowlroll.net/file/4576 ), Rare v1.12 ( http://www.nicovideo.jp/watch/sm8695572 ), Alice magatroid (Nigamon) ( http://www.nicovideo.jp/watch/sm15356096 ). Carsh occurs on all models randomly.
- Q : Will it crash Blender when you hit 'GLSL' button or 'Shadeless' button of 'MMD Shading' panel?
  A : No. I have not experienced about that bug.
- Q :  Does it still happen when using sugiany's master version?
  A : Yes. That's why I moved to this version.

**Comment by powroupi** [comment]
Well, I don't have this issue on my system and the code seems to be fine, so I may not be able to solve it. :cry: 

You might try convert materials manually. If Blender still crash randomly, that probably is the issue of system or Blender. If Blender works fine, there may have some bugs need to be fixed about this operator, and you might convert materials manually at this period. :smile:

**Comment by consilium538** [comment]
Maybe my Computer-like thing is the problem. It often spit out bugs... Thank's for your consideration.

**Comment by powroupi** [comment]
You're welcome. :) Maybe it is caused by other operators, so you might keep tracking the issue and feel free to report issues you find. You can close this issue if you're sure that is the computer issue. Thank you. :smile:

**Comment by PaulBRobinson** [comment]
I just wanted to add that this random crashing happens to me too. There doesn't seem to be a particular model type, but I've noticed it generally only crashes if you click 'Convert Material To Cycles' when you are in any viewport mode that shows materials or textures. So clicking while in 'Solid Viewport Shading' will generally be fine, but if you are in 'Texture' or 'Material' view it will crash.

This could just be my computer, but it has always done this even using sugiany's MMD Tools. Does that information help at all?

Also thanks @powroupi (and everyone else) for all the hard work on MMD Tools.

**Comment by nagadomi** [comment]
I had encountered the same problem several weeks ago. At that time I was using blender 2.79 nightly build on linux, which was then fixed by the update. Perhaps it is a bug of blender and I think that it will fixed in the next version.

**Comment by powroupi** [comment]
>So clicking while in 'Solid Viewport Shading' will generally be fine, but if you are in 'Texture' or 'Material' view it will crash.

Thank you for sharing your experience, @Nabesaka. Maybe @consilium538 could try to see if that will solve his/her issue. :smile: 

>Perhaps it is a bug of blender and I think that it will fixed in the next version.

Yea, I think so, @nagadomi. Or maybe it is a graphic card driver issue and updating driver might solve the issue. :smile:

**Comment by consilium538** [comment]
Strangely, in my computer&blender 2.79, 'Convert Materials for Cycles' butten perfectly work well with in 'Texture' or 'Material' view in several try. I tweak little in blender_mmd_tools/mmd_tools/cycles_converter.py to make MMDBasicShader's reflection from 0.02 to 0, but I think that dosen't make any effect in this weird bug. Anyway I can convert material with no several crash...

**Comment by gitspyder** [comment]
I still have issues with this every now and then and come back here to refresh myself on the solution and realized my fix isn't here, so thought I'd add it.

Solution:
- Change **Shading** to **Solid**
- Change **Engine** to **Blender Render**
- Select Mesh in Outliner
- Then click convert materials to cycles and Blender shouldn't crash
